id: I4A4B2324
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:38.384373
last_modified: 2023-01-04 11:30:38.384384
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  5EFE:
    title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
      Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times In
      the Form of an Aspiration Prayer'
    base_file: 5EFE.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
